### ISSUE TITLE
JSTL does not work?

### ISSUE THREAD

**Issue by officelabotera** [heroku/devcenter-embedded-tomcat#12]
Hello, 

I come from Heroku Dev Center and tried this project, which did not worked with JSTL tag library.
It throws 
"The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application", by just adding original index.jsp page the directive:
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

Can you tell me how do you resolve this please?

Tera

**Comment by saintplay** [comment]
Same problem here

**Comment by saintplay** [comment]
Finally I solved it!  
For anyone having the same trouble, check how I setup my project
<https://github.com/saintplay/susan/tree/385ab73212065b86275de414e5c8421d5ac51a4b>

**Comment by quar17esma** [comment]
Had the same problem. 
I took this [Main.java](https://github.com/heroku/devcenter-embedded-tomcat/blob/master/src/main/java/launch/Main.java) from [Heroku article](https://devcenter.heroku.com/articles/create-a-java-web-application-using-embedded-tomcat) example. There was code that set to skip TLDs. Deleting this code solved the issue.
```java
        //Disable TLD scanning by default
        if (System.getProperty(Constants.SKIP_JARS_PROPERTY) == null && System.getProperty(Constants.SKIP_JARS_PROPERTY) == null) {
            System.out.println("disabling TLD scanning");
            StandardJarScanFilter jarScanFilter = (StandardJarScanFilter) ctx.getJarScanner().getJarScanFilter();
           jarScanFilter.setTldSkip("*");
       }
```
